### ISSUE TITLE
rr_xbox_mapper_node isn't registering soft_estop enable/reset commands

### ISSUE THREAD

**Issue by jack-digilabs** [RoverRobotics/rr_control_input_manager#1]
After running overnight, the xbox mapper node has stopped publishing messages to /cmd_vel/joystick and isn't publishing the soft_estop enable or reset commands. The  error log is below.

[rospy.client][INFO] 2019-01-07 18:49:01,132: init_node, name[/rr_control_input_manager_node], pid[18634]
[xmlrpc][INFO] 2019-01-07 18:49:01,152: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-01-07 18:49:01,155: Started XML-RPC server [http://10.0.7.5:34467/]
[rospy.init][INFO] 2019-01-07 18:49:01,156: ROS Slave URI: [http://10.0.7.5:34467/]
[rospy.impl.masterslave][INFO] 2019-01-07 18:49:01,156: _ready: http://10.0.7.5:34467/
[xmlrpc][INFO] 2019-01-07 18:49:01,157: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-01-07 18:49:01,160: Registering with master node http://10.0.7.5:11311
[rospy.init][INFO] 2019-01-07 18:49:01,256: registered with master
[rospy.rosout][INFO] 2019-01-07 18:49:01,257: initializing /rosout core topic
[rospy.rosout][INFO] 2019-01-07 18:49:01,280: connected to core topic /rosout
[rospy.simtime][INFO] 2019-01-07 18:49:01,297: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-01-07 18:49:01,482: topic[/soft_estop/reset] adding connection to [http://10.0.7.5:36999/], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,487: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,540: topic[/cmd_vel/joystick] adding connection to [http://10.0.7.5:36999/], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,542: topic[/soft_estop/enable] adding connection to [http://10.0.7.5:36999/], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,703: topic[/cmd_vel/managed] adding connection to [/rr_openrover_basic], count 0
[rospy.internal][INFO] 2019-01-07 18:49:02,005: topic[/cmd_vel/managed] adding connection to [/rr_swift_nav_gps_node], count 1
[rospy.internal][INFO] 2019-01-07 18:49:02,665: topic[/cmd_vel/chase] adding connection to [http://10.0.7.5:36552/], count 0
[rosout][WARNING] 2019-01-07 18:50:50,201: [CONTROL_INPUT_MANAGER_NODE] Soft E-Stop Enabled
[rosout][WARNING] 2019-01-07 18:50:50,232: [CONTROL_INPUT_MANAGER_NODE] Soft Estop is still enabled which will prevent any motion
[rospy.internal][INFO] 2019-01-08 09:04:59,783: topic[/cmd_vel/managed] adding connection to [/rostopic_4703_1546959899451], count 2
[rospy.internal][INFO] 2019-01-08 09:05:05,272: topic[/cmd_vel/managed] removing connection to /rostopic_4703_1546959899451
[rospy.internal][INFO] 2019-01-08 09:05:23,914: topic[/rr_control_input_manager/active_controller] adding connection to [/rostopic_4786_1546959923570], count 0
[rospy.internal][INFO] 2019-01-08 09:05:27,303: topic[/rr_control_input_manager/active_controller] removing connection to /rostopic_4786_1546959923570
[rospy.internal][INFO] 2019-01-08 09:08:11,806: topic[/soft_estop/reset] adding connection to [http://10.0.7.5:34917/], count 1
[rospy.internal][ERROR] 2019-01-08 09:08:13,784: Unable to initiate TCP/IP socket to 10.0.7.5:44408 (http://10.0.7.5:34917/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2019-01-08 09:08:14,786: Unknown error initiating TCP/IP socket to 10.0.7.5:44408 (http://10.0.7.5:34917/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2019-01-08 09:08:14,786: topic[/soft_estop/reset] removing connection to http://10.0.7.5:34917/

**Comment by jack-digilabs** [comment]
The previous log was for rr_control_input_manager, the log below is from rr_xbox_mapper.

[rospy.client][INFO] 2019-01-07 18:49:01,200: init_node, name[/rr_xbox_mapper_node], pid[18614]
[xmlrpc][INFO] 2019-01-07 18:49:01,201: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-01-07 18:49:01,204: Started XML-RPC server [http://10.0.7.5:36999/]
[rospy.init][INFO] 2019-01-07 18:49:01,205: ROS Slave URI: [http://10.0.7.5:36999/]
[rospy.impl.masterslave][INFO] 2019-01-07 18:49:01,205: _ready: http://10.0.7.5:36999/
[xmlrpc][INFO] 2019-01-07 18:49:01,207: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-01-07 18:49:01,207: Registering with master node http://10.0.7.5:11311
[rospy.registration][INFO] 2019-01-07 18:49:01,208: Registering publisher topic [/joystick/delay] type [std_msgs/Float32] with master
[rospy.registration][INFO] 2019-01-07 18:49:01,227: Registering publisher topic [/soft_estop/reset] type [std_msgs/Bool] with master
[rospy.registration][INFO] 2019-01-07 18:49:01,240: Registering publisher topic [/move_base/cancel] type [actionlib_msgs/GoalID] with master
[rospy.registration][INFO] 2019-01-07 18:49:01,257: Registering publisher topic [/twgc_hlst/test_mode] type [std_msgs/Bool] with master
[rospy.registration][INFO] 2019-01-07 18:49:01,277: Registering publisher topic [/cmd_vel/joystick] type [geometry_msgs/TwistStamped] with master
[rospy.registration][INFO] 2019-01-07 18:49:01,292: Registering publisher topic [/datarecorder/enable] type [std_msgs/Bool] with master
[rospy.registration][INFO] 2019-01-07 18:49:01,308: Registering publisher topic [/soft_estop/enable] type [std_msgs/Bool] with master
[rospy.init][INFO] 2019-01-07 18:49:01,406: registered with master
[rospy.rosout][INFO] 2019-01-07 18:49:01,407: initializing /rosout core topic
[rospy.rosout][INFO] 2019-01-07 18:49:01,416: connected to core topic /rosout
[rospy.simtime][INFO] 2019-01-07 18:49:01,426: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-01-07 18:49:01,492: topic[/joystick] adding connection to [http://10.0.7.5:44846/], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,498: topic[/soft_estop/reset] adding connection to [/rr_control_input_manager_node], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,544: topic[/cmd_vel/joystick] adding connection to [/rr_control_input_manager_node], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,545: topic[/soft_estop/enable] adding connection to [/rr_control_input_manager_node], count 0
[rospy.internal][INFO] 2019-01-07 18:49:01,688: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-01-07 18:49:02,857: topic[/datarecorder/enable] adding connection to [/image_collection_node], count 0
[rosout][INFO] 2019-01-07 18:50:34,778: User button Y
[rosout][INFO] 2019-01-07 18:50:50,199: User button A
[rospy.internal][INFO] 2019-01-08 09:06:40,817: topic[/cmd_vel/joystick] adding connection to [/rostopic_5066_1546960000480], count 1
[rospy.internal][INFO] 2019-01-08 09:06:46,861: topic[/cmd_vel/joystick] removing connection to /rostopic_5066_1546960000480
